#pragma once

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720
#define SCREEN_COLORBIT 32

#define FRAMERATE 60.0
#define UPDATETIME 800

#define GM_MAX_LIFE 5

#define GM_MAX_ENEMY_BOMB 100
#define GM_MAX_EFFECT_EXPLOSION 100
#define GM_MAX_PARTICLE 1000
#define GM_MAX_ICEFLOOR 2
#define GM_MAX_MUDFLOOR 3

#define GM_MAX_TORNADO 3

#define GM_MAX_MAPSIZE 1500
#define GM_MIN_MAPSIZE 320


#define GM_MAX_ENEMY_SOLDIER 3

